<?

/**
 * @name StandardFramework Constants
 * @author DENFER
 * @copyright DENFER STUDIO
 */

DEFINE ( "INFINITY", 1e+1000 );

DEFINE ( "nil", null );

DEFINE ( "NETWORK_ADDR", "0.0.0.0" );
DEFINE ( "NETWORK_PORT", 7777 );

DEFINE ( "SCREEN_WIDTH", 1 );
DEFINE ( "SCREEN_HEIGHT", 2 );

DEFINE ( "R", "\r" );
DEFINE ( "N", "\n" );
DEFINE ( "RN", R.N );

DEFINE ( "T", "\t" );

DEFINE ( "DEFAULT_INDEX", 0 );

DEFINE ( "MAIN_CAM", DEFAULT_INDEX );
DEFINE ( "MAIN_SPACE", DEFAULT_INDEX );

DEFINE ( "EVENT_CORE", 0xff );
DEFINE ( "EVENT_INIT", 0 + EVENT_CORE );
DEFINE ( "EVENT_LOAD", 1 + EVENT_CORE );
DEFINE ( "EVENT_DRAW", 2 + EVENT_CORE );
DEFINE ( "EVENT_UPDATE", 3 + EVENT_CORE );
DEFINE ( "EVENT_QUIT", 4 + EVENT_CORE );
DEFINE ( "EVENT_TIMER", 5 + EVENT_CORE );

DEFINE ( "TYPE_PRIMITIVES", 0xff );
DEFINE ( "TYPE_OBJECT",  1 );
DEFINE ( "TYPE_SSPRITE", 2 );
DEFINE ( "TYPE_ASPRITE", 3 );
DEFINE ( "TYPE_TEXT", 4 );
DEFINE ( "TYPE_CAMERA", 5);
DEFINE ( "TYPE_SOUND", 6 );
DEFINE ( "TYPE_PPIXEL", 1 + TYPE_PRIMITIVES ); 
DEFINE ( "TYPE_PLINE", 2 + TYPE_PRIMITIVES ); 
DEFINE ( "TYPE_PRECT",  3 + TYPE_PRIMITIVES ); 
DEFINE ( "TYPE_PCIRCLE",  4 + TYPE_PRIMITIVES );
DEFINE ( "TYPE_PELLIPSE",  5 + TYPE_PRIMITIVES );

DEFINE ( "FLAG_NONE", 0 );
DEFINE ( "FLAG_UPDATE", 2 );
DEFINE ( "FLAG_DRAW", 4 );

DEFINE ( "CUT_COUNT", 1 );
DEFINE ( "CUT_SIZE", 2 );


DEFINE ( "K_SYSRQ", 0xB7 );
DEFINE ( "K_PAUSE", 0xC5 );
DEFINE ( "K_ESCAPE", 0x01 );
DEFINE ( "K_ENTER", 0x1C );
DEFINE ( "K_KP_ENTER", 0x9C );

DEFINE ( "K_UP", 0xC8 );
DEFINE ( "K_DOWN", 0xD0 );
DEFINE ( "K_LEFT", 0xCB );
DEFINE ( "K_RIGHT", 0xCD );

DEFINE ( "K_BACKSPACE", 0x0E );
DEFINE ( "K_SPACE", 0x39 );
DEFINE ( "K_TAB", 0x0F );
DEFINE ( "K_TILDE", 0x29 );

DEFINE ( "K_INSERT", 0xD2 );
DEFINE ( "K_DELETE", 0xD3 );
DEFINE ( "K_HOME", 0xC7 );
DEFINE ( "K_END", 0xCF );
DEFINE ( "K_PAGEUP", 0xC9 );
DEFINE ( "K_PAGEDOWN", 0xD1 );

DEFINE ( "K_CTRL", 0xFF - 0x01 );
DEFINE ( "K_CTRL_L", 0x1D );
DEFINE ( "K_CTRL_R", 0x9D );
DEFINE ( "K_ALT", 0xFF - 0x02 );
DEFINE ( "K_ALT_L", 0x38 );
DEFINE ( "K_ALT_R", 0xB8 );
DEFINE ( "K_SHIFT", 0xFF - 0x03 );
DEFINE ( "K_SHIFT_L", 0x2A );
DEFINE ( "K_SHIFT_R", 0x36 );
DEFINE ( "K_SUPER", 0xFF - 0x04 );
DEFINE ( "K_SUPER_L", 0xDB );
DEFINE ( "K_SUPER_R", 0xDC );
DEFINE ( "K_APP_MENU", 0xDD );

DEFINE ( "K_CAPSLOCK", 0x3A );
DEFINE ( "K_NUMLOCK", 0x45 );
DEFINE ( "K_SCROLL", 0x46 );

DEFINE ( "K_BRACKET_L", 0x1A );
DEFINE ( "K_BRACKET_R", 0x1B );
DEFINE ( "K_BACKSLASH", 0x2B );
DEFINE ( "K_SLASH", 0x35 );
DEFINE ( "K_COMMA", 0x33 );
DEFINE ( "K_DECIMAL", 0x34 );
DEFINE ( "K_SEMICOLON", 0x27 );
DEFINE ( "K_APOSTROPHE", 0x28 );

DEFINE ( "K_0", 0x0B );
DEFINE ( "K_1", 0x02 );
DEFINE ( "K_2", 0x03 );
DEFINE ( "K_3", 0x04 );
DEFINE ( "K_4", 0x05 );
DEFINE ( "K_5", 0x06 );
DEFINE ( "K_6", 0x07 );
DEFINE ( "K_7", 0x08 );
DEFINE ( "K_8", 0x09 );
DEFINE ( "K_9", 0x0A );

DEFINE ( "K_MINUS", 0x0C );
DEFINE ( "K_EQUALS", 0x0D );

DEFINE ( "K_A", 0x1E );
DEFINE ( "K_B", 0x30 );
DEFINE ( "K_C", 0x2E );
DEFINE ( "K_D", 0x20 );
DEFINE ( "K_E", 0x12 );
DEFINE ( "K_F", 0x21 );
DEFINE ( "K_G", 0x22 );
DEFINE ( "K_H", 0x23 );
DEFINE ( "K_I", 0x17 );
DEFINE ( "K_J", 0x24 );
DEFINE ( "K_K", 0x25 );
DEFINE ( "K_L", 0x26 );
DEFINE ( "K_M", 0x32 );
DEFINE ( "K_N", 0x31 );
DEFINE ( "K_O", 0x18 );
DEFINE ( "K_P", 0x19 );
DEFINE ( "K_Q", 0x10 );
DEFINE ( "K_R", 0x13 );
DEFINE ( "K_S", 0x1F );
DEFINE ( "K_T", 0x14 );
DEFINE ( "K_U", 0x16 );
DEFINE ( "K_V", 0x2F );
DEFINE ( "K_W", 0x11 );
DEFINE ( "K_X", 0x2D );
DEFINE ( "K_Y", 0x15 );
DEFINE ( "K_Z", 0x2C );

DEFINE ( "K_KP_0", 0x52 );
DEFINE ( "K_KP_1", 0x4F );
DEFINE ( "K_KP_2", 0x50 );
DEFINE ( "K_KP_3", 0x51 );
DEFINE ( "K_KP_4", 0x4B );
DEFINE ( "K_KP_5", 0x4C );
DEFINE ( "K_KP_6", 0x4D );
DEFINE ( "K_KP_7", 0x47 );
DEFINE ( "K_KP_8", 0x48 );
DEFINE ( "K_KP_9", 0x49 );

DEFINE ( "K_KP_SUB", 0x4A );
DEFINE ( "K_KP_ADD", 0x4E );
DEFINE ( "K_KP_MUL", 0x37 );
DEFINE ( "K_KP_DIV", 0xB5 );
DEFINE ( "K_KP_DECIMAL", 0x53 );

DEFINE ( "K_F1", 0x3B );
DEFINE ( "K_F2", 0x3C );
DEFINE ( "K_F3", 0x3D );
DEFINE ( "K_F4", 0x3E );
DEFINE ( "K_F5", 0x3F );
DEFINE ( "K_F6", 0x40 );
DEFINE ( "K_F7", 0x41 );
DEFINE ( "K_F8", 0x42 );
DEFINE ( "K_F9", 0x43 );
DEFINE ( "K_F10", 0x44 );
DEFINE ( "K_F11", 0x57 );
DEFINE ( "K_F12", 0x58 );

DEFINE ( "KA_DOWN", 0 );
DEFINE ( "KA_UP", 1 );


DEFINE ( "REFRESH_MAXIMUM", 0 );
DEFINE ( "REFRESH_DEFAULT", 1 );

DEFINE ( "M_BLEFT", 0 );
DEFINE ( "M_BMIDDLE", 1 );
DEFINE ( "M_BRIGHT", 2 );
DEFINE ( "M_WUP", 0 );
DEFINE ( "M_WDOWN", 1 );

DEFINE ( "MONITOR_DEFAULTTOPRIMARY", 0x00000001 );

DEFINE ( "PNG_FILTER_NONE", 0 );
DEFINE ( "PNG_FILTER_SUB", 1 );
DEFINE ( "PNG_FILTER_UP", 2 );
DEFINE ( "PNG_FILTER_AVERAGE", 3 );
DEFINE ( "PNG_FILTER_PAETH", 4 );

DEFINE ( "PNG_COLOR_GRAYSCALE", 0 );
DEFINE ( "PNG_COLOR_RGB", 2 );
DEFINE ( "PNG_COLOR_PALETTE", 3 );
DEFINE ( "PNG_COLOR_GRAYSCALEALPHA", 4 );
DEFINE ( "PNG_COLOR_RGBALPHA", 6 );

DEFINE ( "TEXT_HALIGN_LEFT", 0x000001 );
DEFINE ( "TEXT_HALIGN_CENTER", 0x000002 );
DEFINE ( "TEXT_HALIGN_RIGHT", 0x000004 );
DEFINE ( "TEXT_HALIGN_JUSTIFY", 0x000008 );
DEFINE ( "TEXT_VALIGN_TOP", 0x000010 );
DEFINE ( "TEXT_VALIGN_CENTER", 0x000020 );
DEFINE ( "TEXT_VALIGN_BOTTOM", 0x000040 );
DEFINE ( "TEXT_FX_VCA", 0x000080 );
DEFINE ( "TEXT_FX_LENGTH", 0x000100 );

DEFINE ( "TEX_MIPMAP", 0x000001 );
DEFINE ( "TEX_CLAMP", 0x000002 );
DEFINE ( "TEX_REPEAT", 0x000004 );
DEFINE ( "TEX_COMPRESS", 0x000008 );

DEFINE ( "TEX_CONVERT_TO_POT", 0x000010 );
DEFINE ( "TEX_CALCULATE_ALPHA", 0x000020 );

DEFINE ( "TEX_GRAYSCALE", 0x000040 );
DEFINE ( "TEX_INVERT", 0x000080 );
DEFINE ( "TEX_CUSTOM_EFFECT", 0x000100 );

DEFINE ( "TEX_FILTER_NEAREST", 0x000200 );
DEFINE ( "TEX_FILTER_LINEAR", 0x000400 );
DEFINE ( "TEX_FILTER_BILINEAR", 0x000800 );
DEFINE ( "TEX_FILTER_TRILINEAR", 0x001000 );
DEFINE ( "TEX_FILTER_ANISOTROPY", 0x002000 );

DEFINE ( "TEX_DEFAULT_2D", TEX_CLAMP | TEX_FILTER_LINEAR | TEX_CONVERT_TO_POT | TEX_CALCULATE_ALPHA );

DEFINE ( "RT_TYPE_PBUFFER", 0 );
DEFINE ( "RT_TYPE_FBO", 1 );

DEFINE ( "RT_DEFAULT", 0x00 );
DEFINE ( "RT_FULL_SCREEN", 0x01 );
DEFINE ( "RT_USE_DEPTH", 0x02 );
DEFINE ( "RT_CLEAR_COLOR", 0x04 );
DEFINE ( "RT_CLEAR_DEPTH", 0x08 );

DEFINE ( "RT_FORCE_PBUFFER", 0x100000 );

DEFINE ( "PR2D_FILL", 0x010000 );
DEFINE ( "PR2D_SMOOTH", 0x020000 );

DEFINE ( "FX_BLEND_NORMAL", 0x00 );
DEFINE ( "FX_BLEND_ADD", 0x01 );
DEFINE ( "FX_BLEND_MULT", 0x02 );
DEFINE ( "FX_BLEND_BLACK", 0x03 );
DEFINE ( "FX_BLEND_WHITE", 0x04 );
DEFINE ( "FX_BLEND_MASK", 0x05 );

DEFINE ( "FX_COLOR_MIX", 0x00 );
DEFINE ( "FX_COLOR_SET", 0x01 );

DEFINE ( "FX2D_FLIPX", 0x000001 );
DEFINE ( "FX2D_FLIPY", 0x000002 );
DEFINE ( "FX2D_VCA", 0x000004 );
DEFINE ( "FX2D_VCHANGE", 0x000008 );
DEFINE ( "FX2D_SCALE", 0x000010 );

DEFINE ( "FX_BLEND", 0x100000 );
DEFINE ( "FX_COLOR", 0x200000 );

DEFINE ( "JS_EVENT_BUTTON", 0x01 );
DEFINE ( "JS_EVENT_AXIS", 0x02 );
DEFINE ( "JS_EVENT_INIT", 0x80 );

DEFINE ( "JSIOCGNAME", -2142213613 );
DEFINE ( "JSIOCGAXMAP", -2143262158 );
DEFINE ( "JSIOCGAXES", -2147390959 );
DEFINE ( "JSIOCGBUTTONS", -2147390958 );

DEFINE ( "JOY_POVCENTERED", -1 );
DEFINE ( "JOY_POVFORWARD", 0 );
DEFINE ( "JOY_POVRIGHT", 9000 );
DEFINE ( "JOY_POVBACKWARD", 18000 );
DEFINE ( "JOY_POVLEFT", 27000 );
DEFINE ( "JOY_RETURNX", 1 );
DEFINE ( "JOY_RETURNY", 2 );
DEFINE ( "JOY_RETURNZ", 4 );
DEFINE ( "JOY_RETURNR", 8 );
DEFINE ( "JOY_RETURNU", 16 );
DEFINE ( "JOY_RETURNV", 32 );
DEFINE ( "JOY_RETURNPOV", 64 );
DEFINE ( "JOY_RETURNBUTTONS", 128 );
DEFINE ( "JOY_RETURNRAWDATA", 256 );
DEFINE ( "JOY_RETURNPOVCTS", 512 );
DEFINE ( "JOY_RETURNCENTERED", 0x400 );
DEFINE ( "JOY_USEDEADZONE", 0x800 );

DEFINE ( "JOY_HAS_Z", 0x000001 );
DEFINE ( "JOY_HAS_R", 0x000002 );
DEFINE ( "JOY_HAS_U", 0x000004 );
DEFINE ( "JOY_HAS_V", 0x000008 );
DEFINE ( "JOY_HAS_POV", 0x000010 );

DEFINE ( "JOY_AXIS_X", 0 );
DEFINE ( "JOY_AXIS_Y", 1 );
DEFINE ( "JOY_AXIS_Z", 2 );
DEFINE ( "JOY_AXIS_R", 3 );
DEFINE ( "JOY_AXIS_U", 4 );
DEFINE ( "JOY_AXIS_V", 5 );
DEFINE ( "JOY_POVX", 6 );
DEFINE ( "JOY_POVY", 7 );

DEFINE ( "cs_ZenGL", 'ZenGL 0.2.4' );
DEFINE ( "cs_Date", '2011.12.04' );
DEFINE ( "cv_major", 0 );
DEFINE ( "cv_minor", 2 );
DEFINE ( "cv_revision", 4 );

DEFINE ( "pi", 3.141592654 );
DEFINE ( "rad2deg", 57.29578049 );
DEFINE ( "deg2rad", 0.017453292 );

DEFINE ( "ORIENTATION_LEFT", -1 );
DEFINE ( "ORIENTATION_RIGHT", 1 );
DEFINE ( "ORIENTATION_ZERO", 0 );